### ISSUE TITLE
Conflicts with Modmenu

### ISSUE THREAD

**Issue by Vewaa** [burgerguy/HUDTweaks#3]
Can't open the game with ModMenu mod. 
Error: The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'modmenu'!
(Deleted all mods and stayed only Modmenu and your plugin)

Mods, I use: 
![image](https://user-images.githubusercontent.com/72296110/108837876-f433e600-75e3-11eb-9bba-495332779f55.png)

**Comment by burgerguy** [comment]
I think this is because the ModMenu version you are using is out of date. I would recommend updating to the latest one and seeing if it still works. I think the latest version can be found on the TerraformersMC maven repo, and you can find a jar for ModMenu v1.16.8, which works with 1.16.5, or v2.0.0-snapshot, which works with 1.17 snapshots.
